#!/bin/bash
# Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# This script is meant to make this package available in the canonical location
# when running on Travis CI. This is useful for anyone who wishes to run Travis
# CI against their fork of the repo.
if [[ ! -d "$HOME/gopath/src/github.com/awslabs/ecs-task-kite" ]]; then
	mkdir -p "$HOME/gopath/src/github.com/awslabs"
	ln -s "$(pwd)" "$HOME/gopath/src/github.com/awslabs/ecs-task-kite"
fi
